### ISSUE TITLE
your-portfolio-pmmachadov

### ISSUE THREAD

**Issue by cramirez16** [pmmachadov/pmmachadov#4]
Hola Pablo,
podrías incluir un ReadMe.md con una breve descripción de tu proyecto,
también podrías añadir un archivo .gitignore, de esta manera evitarás subir a github archivos y directorios innecesarios.
Esto será más importante cuando uses librerías, por ejemplo, no deberías subir a github la carpeta node_modules.
En este proyecto en particular, es posible que no sea necesario subir a github:
.vscode, .github, .devcontainer y .content.
Un saludo y buen trabajo :-)

**Comment by pmmachadov** [comment]
Thank you Carlos. This is done.
